### ISSUE TITLE
[1.16.5] Multiplayer Client crash upon entering pocket dimension

### ISSUE THREAD

**Issue by Da-Boom** [TheCosmicNebula/DimensionalPocketsII#70]
I am testing this for a small private multiplayer modpack, based off of the Create 101 v2 modpack

i logged in, and immediately gave myself a pocket dimension, and tried to enter it... i immediately crashed with the linked crash log

[Crash Log](https://paste.ee/p/ildjL)

I am running Minecraft 1.16.5 with forge version 36.0.37 on both the client and server (though i did try upgrading after to forge 36.1.0 and no dice- same issue)
using openjdk 1.8.0_282

The Server itself had no errors - it was a client side crash

**Comment by TheCosmicNebula** [comment]
Hi, this issue is already fixed for the upcoming release. I'm am working on making it public as soon as possible.
