### ISSUE TITLE
Bug: Input/Output not functioning properly

### ISSUE THREAD

**Issue by pokebro2000** [TheCosmicNebula/DimensionalPocketsII#73]
Can not interact with inputs and outputs from outside the pocket; attaching cables (Using mekanism, although other mods have been attempted) does not extract FE from output sides, and inserting FE through input drains the power but does not charge the dimension itself (essentially voids it). Sides do not recognise pipes for fluids, either, and do not connect inside or outside the pocket. Currently using 1.16.5-1.0.74 Universal.

**Comment by TheCosmicNebula** [comment]
I am aware if this, these features are currently a work in progress.
