### ISSUE TITLE
[1.16.5] Dimensional Tome duplicates itself when loading an existing world

### ISSUE THREAD

**Issue by HieronymousPhantom** [TheCosmicNebula/DimensionalPocketsII#77]
**MC Version**: 1.16.5
**Mod Version**: 1.2.0
**CosLib Version**: 6.1.0
Running on **Client**

After installing the mod fresh to an existing world, I received the tome in my inventory as normal. I opened it once and glanced around a bit but didn't do anything major with it before putting it in the Locker (from BetterStorageToo) I use to store books. After logging off for the night and opening my world again the next day, I got another tome in my inventory as if I hadn't gotten one before. It doesn't duplicate itself if I have the tome in my inventory, but I don't usually log out with guidebooks in my inventory unless I'm actively using them.

The extra book is easily removable, more of a minor annoyance than anything, but I thought it should be brought to your attention regardless.

**Comment by TheCosmicNebula** [comment]
Hi,

Many thanks for the thorough report. I am aware of this issue, and have tried many things to fix it. It is on the list to be fixed. For now you can use the Config options to disable being given the Tome, which stops you being given one every time you load the world.

**Comment by HieronymousPhantom** [comment]
Oh! So many of my mods didn't have an in-game config that I completely forgot to check there to see. Apologies for the redundant report.
