### ISSUE TITLE
Mana and Artiface blink can go through walls

### ISSUE THREAD

**Issue by tyggna** [TheCosmicNebula/DimensionalPocketsII#78]
Yeah, I'm putting together a magic themed modpack and the Mana and Artiface blink spell can teleport me right out of my pocket chunk and into someone elses.  I'll raise this issue with them and see if they can have spell effects disabled by dimension as well, but since you already have disallowed items and blocks in your config, I figured you could probably get this in quicker.

**Comment by TheCosmicNebula** [comment]
Many thanks for the report. I will download the mod and add those items to the blacklist.

**Comment by TheCosmicNebula** [comment]
I have looked into this issue, and from my end, without disabling ALL spells, books etc I cannot stop this behaviour. I have added an issue to their github page, but they dont seem to be responding at the moment.

**Comment by TheCosmicNebula** [comment]
I have decided to cancel all spells inside the Pocket Dimension.
