### ISSUE TITLE
Compatibility issue with Money and Sign Shops

### ISSUE THREAD

**Issue by Charmanth** [TheCosmicNebula/DimensionalPocketsII#79]
So there seems to be a compatibility issue with this mod and Money and Sign Shops.  [Crash Repor](https://paste.ee/p/UcgG3)t (link valid for only a month!) indicates that the two mods interact when the pocket block is interacted with.  I don't know whose side needs to do the fix, so I'm gonna post a report there, too, and reference this report.  I have tested this on both a server and in single player, and it happens in both.

Please let me know if you can fix this!

**Comment by TheCosmicNebula** [comment]
Hi, many thanks for the crash report. Unfortunately I am unable to download the report due to my Antivirus. Are you able to post the log here directly?

**Comment by TheCosmicNebula** [comment]
Hold that, I am able to look at it now.

**Comment by Charmanth** [comment]
Thank you so much, looking forward to a possible fix!

**Comment by TheCosmicNebula** [comment]
This issue has now been fixed. Stupid null value! This fix will be in the next release.
